version: '3.10'

services:
  db:
    image: postgres:15.3-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: 1234567
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
  web:
    container_name: syshammer_userauth
    build:
      context: ./
      dockerfile: Dockerfile
    command: bash -c "python /usr/src/syshammer_userauth/manage.py migrate --noinput &&
             python /usr/src/syshammer_userauth/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/usr/src/syshammer_userauth
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db
volumes:
  postgres_data:
#
#
#version: '3.10'
#
#services:
#  db:
#    image: postgres:15.17-alpine
#    volumes:
#      - postgres_data:/var/lib/postgresql/data/
#    environment:
#      - POSTGRES_PASSWORD=postgres
#  web:
#    build: .
#    command: python /usr/src/syshammer_userauth/manage.py runserver 0.0.0.0:8000
#    volumes:
#      - .:/usr/src/syshammer_userauth
#    ports:
#      - "8000:8000"
#    environment:
#      - POSTGRES_NAME=postgres
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=postgres
#    depends_on:
#      - db
#volumes:
#  postgres_data: